### ISSUE TITLE
OCRA bundler issues

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#100]
For private gems on windows metanorma.exe fails with error:

<details><summary>Stacktrace</summary>
<p>

```
C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/git/git_proxy.rb:223:in `allowed_with_path': The git source https://github.com/metanorma/metanorma-cli is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/git/git_proxy.rb:193:in `find_local_revision'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/git/git_proxy.rb:65:in `revision'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/git.rb:228:in `revision'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/git.rb:95:in `install_path'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/path.rb:133:in `expanded_path'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/path.rb:174:in `load_spec_files'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/git.rb:203:in `load_spec_files'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/path.rb:107:in `local_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/source/git.rb:170:in `specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/definition.rb:781:in `block in converge_locked_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/definition.rb:767:in `each'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/definition.rb:767:in `converge_locked_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/definition.rb:269:in `resolve'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/definition.rb:183:in `specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/definition.rb:253:in `specs_for'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/definition.rb:235:in `requested_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/runtime.rb:91:in `block in definition_method'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/runtime.rb:20:in `setup'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler.rb:148:in `setup'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/ui/shell.rb:136:in `with_level'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/ui/shell.rb:88:in `silence'
	from C:/Users/runneradmin/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.17/lib/bundler/setup.rb:20:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrCE20.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrCE20.tmp/src/metanorma:5:in `<main>'
```

</p>
</details>

Cases:
 - https://github.com/metanorma/mn-samples-nist/pull/63#issuecomment-850951436
 - https://github.com/metanorma/mn-samples-bipm/pull/33#issuecomment-850951551
 - https://github.com/metanorma/mn-samples-bsi/pull/36#issuecomment-850951629

**Comment by CAMOBAP** [comment]
More details here https://github.com/metanorma/packed-mn/pull/103#issuecomment-868470551

**Comment by ronaldtse** [comment]
All done.
