### ISSUE TITLE
Ping to www.iso.org causing Metanorma to crash behind firewall

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#107]
https://github.com/metanorma/packed-mn/blob/5c8aefe418b8c0794e006db7b4f2933877962607/bin/metanorma#L177-L191

This is the cause of https://github.com/relaton/relaton/issues/92

User reports receiving this message:

```
$ metanorma --type iso foobar.adoc
 
/__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to www.iso.org:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:902:in `connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:876:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:608:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:485:in `get_response'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:462:in `get'
from /__enclose_io_memfs__/local/metanorma:179:in `<main>'
```

This failure is due to the user being behind a corporate proxy, and unable to connect to www.iso.org.

This user should be running the latest version, he installed via homebrew (`brew install metanorma/metanorma/metanorma`).

```
bash-3.2$ metanorma -v
/__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect': Failed to open TCP connection to www.iso.org:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:902:in `connect'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:876:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:608:in `start'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:485:in `get_response'
from /__enclose_io_memfs__/lib/ruby/2.4.0/net/http.rb:462:in `get'
from /__enclose_io_memfs__/local/metanorma:179:in `<main>'
bash-3.2$ 
```

**Comment by ronaldtse** [comment]
In addition, this users needs to access the internet via a corporate proxy (SOCKS). Therefore any kind of internet request will fail in this case.

**Comment by ronaldtse** [comment]
@CAMOBAP can this be closed now? Thanks.
