### ISSUE TITLE
Some failures in Windows execution of Metanorma binary

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#115]
https://github.com/metanorma/ogc-citygml-xmi/pull/30/checks?check_run_id=3447104241

```
C:/Users/RUNNER~1/AppData/Local/Temp/ocrCB17.tmp/lib/ruby/site_ruby/2.5.0/bundler/source/git/git_proxy.rb:221:in `allowed_with_path': The git source git@github.com:metanorma/metanorma-plugin-lutaml.git is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocrCB17.tmp/lib/ruby/site_ruby/2.5.0/bundler/source/git/git_proxy.rb:191:in `find_local_revision'
```

**Comment by CAMOBAP** [comment]
This is a known issue https://github.com/metanorma/packed-mn/issues/100

Unfortunatelly I haven't time to look at it right now
