### ISSUE TITLE
Windows 1.4.15pre failure

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#116]
```
C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/i18n-1.8.10/lib/i18n/tests/lookup.rb:12:in `test': wrong number of arguments (given 1, expected 2) (ArgumentError)
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/i18n-1.8.10/lib/i18n/tests/lookup.rb:12:in `<module:Lookup>'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/i18n-1.8.10/lib/i18n/tests/lookup.rb:5:in `<module:Tests>'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/i18n-1.8.10/lib/i18n/tests/lookup.rb:4:in `<module:I18n>'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/i18n-1.8.10/lib/i18n/tests/lookup.rb:3:in `<top (required)>'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:489:in `require'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:489:in `const_get'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:489:in `block (3 levels) in attempt_load_autoload'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:483:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:483:in `block (2 levels) in attempt_load_autoload'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:481:in `each'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:481:in `block in attempt_load_autoload'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:475:in `loop'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:475:in `attempt_load_autoload'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:734:in `build_exe'
	from C:/hostedtoolcache/windows/Ruby/2.5.9/x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.11/bin/ocra:1231:in `block in <top (required)>'
```

cc @ronaldtse

**Comment by ronaldtse** [comment]
Looks like an incompatibility in Ocra with the i18n gem? Gem and Ruby version issues?

**Comment by CAMOBAP** [comment]
@ronaldtse yep looks like, I didn't checked deeply yet, but I will investigate

**Comment by CAMOBAP** [comment]
Fixed
