### ISSUE TITLE
Occasional segmentation fault when fetching Relaton from ITU

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#129]
https://github.com/metanorma/packed-mn/runs/4420287475?check_suite_focus=true#logs

Not sure what the cause is.

```
[info]: Compiling /home/runner/work/packed-mn/packed-mn/build/itu/sources/G.191.adoc ...
[relaton] Info: detecting backends:
[relaton-itu] ("ITU-T G.728") fetching...
[relaton-itu] ("ITU-T G.726") fetching...
/__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-cookie-1.0.4/lib/http/cookie_jar.rb:18: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0022 p:---- s:0169 e:000168 CFUNC  :require
c:0021 p:0058 s:0164 e:000163 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-cookie-1.0.4/lib/http/cookie_jar.rb:18 [FINISH]
c:0020 p:0025 s:0158 e:000155 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/http-cookie-1.0.4/lib/http/cookie_jar.rb:74 [FINISH]
c:0019 p:---- s:0150 e:000149 CFUNC  :new
c:0018 p:0035 s:0146 e:000145 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/mechanize-2.8.3/lib/mechanize/http/agent.rb:144 [FINISH]
c:0017 p:---- s:0141 e:000140 CFUNC  :new
c:0016 p:0020 s:0136 e:000135 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/mechanize-2.8.3/lib/mechanize.rb:192 [FINISH]
c:0015 p:---- s:0131 e:000130 CFUNC  :new
c:0014 p:0034 s:0127 e:000126 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-itu-1.9.0/lib/relaton_itu/hit_collection.rb:23 [FINISH]
c:0013 p:---- s:0120 e:000119 CFUNC  :new
c:0012 p:0132 s:0114 e:000113 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-itu-1.9.0/lib/relaton_itu/itu_bibliography.rb:28
c:0011 p:0165 s:0106 e:000105 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-itu-1.9.0/lib/relaton_itu/itu_bibliography.rb:92
c:0010 p:0008 s:0089 e:000088 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-itu-1.9.0/lib/relaton_itu/itu_bibliography.rb:139
c:0009 p:0091 s:0080 e:000079 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-itu-1.9.0/lib/relaton_itu/itu_bibliography.rb:50
c:0008 p:0021 s:0070 e:000069 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-itu-1.9.0/lib/relaton_itu/processor.rb:17
c:0007 p:0020 s:0063 e:000062 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:431
c:0006 p:0020 s:0053 e:000052 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:416
c:0005 p:0270 s:0041 e:000038 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:396
c:0004 p:0107 s:0024 e:000023 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:74
c:0003 p:0021 s:0013 e:000011 BLOCK  /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:109
c:0002 p:0011 s:0007 e:000006 BLOCK  /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/workers_pool.rb:11 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]
```

**Comment by ronaldtse** [comment]
Also crashed in fetching from ISO:
https://github.com/metanorma/packed-mn/runs/4443597519?check_suite_focus=true

<details>

```
2021-12-07T12:16:02.3824740Z build/metanorma site generate build/cc -c build/cc/metanorma.yml -o site/cc --agree-to-terms
2021-12-07T12:16:02.3848054Z Cloning into 'build/cc'...
2021-12-07T12:16:24.8042059Z [info]: Compiling /home/runner/work/packed-mn/packed-mn/build/cc/sources/cc-18011.adoc ...
2021-12-07T12:16:24.9580811Z [relaton] Info: detecting backends:
2021-12-07T12:16:44.5449302Z [relaton-ietf] ("IETF RFC 6350") fetching...
2021-12-07T12:16:44.5494016Z [relaton-iso] ("ISO 8601") fetching...
2021-12-07T12:16:44.5783225Z [relaton-iso] ("ISO/IEC 646") fetching...
2021-12-07T12:16:44.5816034Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:157: [BUG] Segmentation fault at 0x0000000000000000
2021-12-07T12:16:44.5817506Z ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
2021-12-07T12:16:44.5817982Z 
2021-12-07T12:16:44.5818968Z -- Control frame information -----------------------------------------------
2021-12-07T12:16:44.5820059Z c:0031 p:---- s:0228 e:000227 CFUNC  :require
2021-12-07T12:16:44.5821445Z c:0030 p:0039 s:0223 e:000222 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:157
2021-12-07T12:16:44.5823162Z c:0029 p:0103 s:0217 e:000216 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:101
2021-12-07T12:16:44.5824843Z c:0028 p:0114 s:0211 e:000210 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:103
2021-12-07T12:16:44.5826543Z c:0027 p:0006 s:0205 e:000204 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:91
2021-12-07T12:16:44.5828221Z c:0026 p:0021 s:0200 e:000199 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:73
2021-12-07T12:16:44.5829898Z c:0025 p:0027 s:0196 e:000195 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:133
2021-12-07T12:16:44.5831584Z c:0024 p:0010 s:0190 e:000189 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/multi_json-1.15.0/lib/multi_json.rb:139
2021-12-07T12:16:44.5833326Z c:0023 p:0029 s:0184 e:000183 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/helpers.rb:7
2021-12-07T12:16:44.5835196Z c:0022 p:0060 s:0179 e:000178 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:125
2021-12-07T12:16:44.5837482Z c:0021 p:0050 s:0172 e:000169 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:95
2021-12-07T12:16:44.5839539Z c:0020 p:0137 s:0161 e:000160 BLOCK  /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:58 [FINISH]
2021-12-07T12:16:44.5840718Z c:0019 p:---- s:0152 e:000151 CFUNC  :each
2021-12-07T12:16:44.5841813Z c:0018 p:0020 s:0148 e:000147 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:50
2021-12-07T12:16:44.5843387Z c:0017 p:0027 s:0139 e:000138 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:27
2021-12-07T12:16:44.5844794Z c:0016 p:0032 s:0131 e:000130 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/search_index.rb:927
2021-12-07T12:16:44.5846229Z c:0015 p:0075 s:0125 e:000124 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/hit_collection.rb:81
2021-12-07T12:16:44.5847759Z c:0014 p:0027 s:0117 e:000116 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/hit_collection.rb:14 [FINISH]
2021-12-07T12:16:44.5848790Z c:0013 p:---- s:0112 e:000111 CFUNC  :new
2021-12-07T12:16:44.5849935Z c:0012 p:0019 s:0107 e:000106 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:15
2021-12-07T12:16:44.5851459Z c:0011 p:0046 s:0101 e:000100 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:96
2021-12-07T12:16:44.5853159Z c:0010 p:0008 s:0091 e:000090 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:189
2021-12-07T12:16:44.5854943Z c:0009 p:0102 s:0082 e:000081 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:42
2021-12-07T12:16:44.5856558Z c:0008 p:0021 s:0070 e:000069 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/processor.rb:19
2021-12-07T12:16:44.5858034Z c:0007 p:0020 s:0063 e:000062 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:431
2021-12-07T12:16:44.5859406Z c:0006 p:0020 s:0053 e:000052 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:416
2021-12-07T12:16:44.5860768Z c:0005 p:0270 s:0041 e:000038 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:396
2021-12-07T12:16:44.5862112Z c:0004 p:0107 s:0024 e:000023 METHOD /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:74
2021-12-07T12:16:44.5863471Z c:0003 p:0021 s:0013 e:000011 BLOCK  /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:109
2021-12-07T12:16:44.5864923Z c:0002 p:0011 s:0007 e:000006 BLOCK  /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/workers_pool.rb:11 [FINISH]
2021-12-07T12:16:44.5865967Z c:0001 p:---- s:0003 e:000002 (none) [FINISH]
2021-12-07T12:16:44.5866423Z 
2021-12-07T12:16:44.5867168Z -- Ruby level backtrace information ----------------------------------------
2021-12-07T12:16:44.5868434Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
2021-12-07T12:16:44.5869801Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:109:in `block in fetch_async'
2021-12-07T12:16:44.5871038Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:74:in `fetch'
2021-12-07T12:16:44.5872294Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:396:in `check_bibliocache'
2021-12-07T12:16:44.5873648Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:416:in `new_bib_entry'
2021-12-07T12:16:44.5875080Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-1.9.5/lib/relaton/db.rb:431:in `net_retry'
2021-12-07T12:16:44.5876486Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/processor.rb:19:in `get'
2021-12-07T12:16:44.5877995Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:42:in `get'
2021-12-07T12:16:44.5879596Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:189:in `isobib_get1'
2021-12-07T12:16:44.5881363Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:96:in `isobib_search_filter'
2021-12-07T12:16:44.5883003Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:15:in `search'
2021-12-07T12:16:44.5884564Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/iso_bibliography.rb:15:in `new'
2021-12-07T12:16:44.5886246Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/hit_collection.rb:14:in `initialize'
2021-12-07T12:16:44.5887699Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/relaton-iso-1.9.1/lib/relaton_iso/hit_collection.rb:81:in `fetch_iso'
2021-12-07T12:16:44.5889055Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/search_index.rb:927:in `search'
2021-12-07T12:16:44.5890392Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:27:in `read'
2021-12-07T12:16:44.5891773Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:50:in `request'
2021-12-07T12:16:44.5902574Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:50:in `each'
2021-12-07T12:16:44.5904063Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:58:in `block in request'
2021-12-07T12:16:44.5905528Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:95:in `build_request'
2021-12-07T12:16:44.5906942Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/transport/transport.rb:125:in `build_body'
2021-12-07T12:16:44.5908248Z /__ruby_packer_memfs__/local/vendor/bundle/ruby/2.6.0/gems/algolia-2.1.1/lib/algolia/helpers.rb:7:in `to_json'
...
2021-12-07T12:16:45.0443122Z 7f269a6a7000-7f269a6a8000 r--p 00002000 08:01 3491                       /usr/lib/x86_64-linux-gnu/libutil-2.31.so
2021-12-07T12:16:45.0444317Z 7f269a6a8000-7f269a6a9000 r--p 00002000 08:01 3491                       /usr/lib/x86_64-linux-gnu/libutil-2.31.so
2021-12-07T12:16:45.0445505Z 7f269a6a9000-7f269a6aa000 rw-p 00003000 08:01 3491                       /usr/lib/x86_64-linux-gnu/libutil-2.31.so
2021-12-07T12:16:45.0446822Z 7f269a6aa000-7f269a6b9000 r--p 00000000 08:01 3455                       /usr/lib/x86_64-linux-gnu/libm-2.31.so
2021-12-07T12:16:45.0447982Z 7f269a6b9000-7f269a760000 r-xp 0000f000 08:01 3455                       /usr/lib/x86_64-linux-gnu/libm-2.31.so
2021-12-07T12:16:45.0449108Z 7f269a760000-7f269a7f7000 r--p 000b6000 08:01 3455                       /usr/lib/x86_64-linux-gnu/libm-2.31.so
2021-12-07T12:16:45.0450208Z 7f269a7f7000-7f269a7f8000 r--p 0014c000 08:01 3455                       /usr/lib/x86_64-linux-gnu/libm-2.31.so
2021-12-07T12:16:45.0451414Z 7f269a7f8000-7f269a7f9000 rw-p 0014d000 08:01 3455                       /usr/lib/x86_64-linux-gnu/libm-2.31.so
2021-12-07T12:16:45.0452770Z 7f269a7f9000-7f269a7fb000 r--p 00000000 08:01 3472                       /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
2021-12-07T12:16:45.0453995Z 7f269a7fb000-7f269a810000 r-xp 00002000 08:01 3472                       /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
2021-12-07T12:16:45.0455238Z 7f269a810000-7f269a82a000 r--p 00017000 08:01 3472                       /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
2021-12-07T12:16:45.0456441Z 7f269a82a000-7f269a82b000 r--p 00030000 08:01 3472                       /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
2021-12-07T12:16:45.0457638Z 7f269a82b000-7f269a82c000 rw-p 00031000 08:01 3472                       /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
2021-12-07T12:16:45.0458584Z 7f269a82c000-7f269a834000 rw-p 00000000 00:00 0 
2021-12-07T12:16:45.0459547Z 7f269a834000-7f269a835000 r--p 00000000 08:01 3454                       /usr/lib/x86_64-linux-gnu/libdl-2.31.so
2021-12-07T12:16:45.0460634Z 7f269a835000-7f269a837000 r-xp 00001000 08:01 3454                       /usr/lib/x86_64-linux-gnu/libdl-2.31.so
2021-12-07T12:16:45.0461784Z 7f269a837000-7f269a838000 r--p 00003000 08:01 3454                       /usr/lib/x86_64-linux-gnu/libdl-2.31.so
2021-12-07T12:16:45.0462800Z 7f269a838000-7f269a839000 r--p 00003000 08:01 3454                       /usr/lib/x86_64-linux-gnu/libdl-2.31.so
2021-12-07T12:16:45.0463807Z 7f269a839000-7f269a83a000 rw-p 00004000 08:01 3454                       /usr/lib/x86_64-linux-gnu/libdl-2.31.so
2021-12-07T12:16:45.0464835Z 7f269a83a000-7f269a83d000 r--p 00000000 08:01 3489                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
2021-12-07T12:16:45.0465869Z 7f269a83d000-7f269a841000 r-xp 00003000 08:01 3489                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
2021-12-07T12:16:45.0466887Z 7f269a841000-7f269a842000 r--p 00007000 08:01 3489                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
2021-12-07T12:16:45.0467886Z 7f269a842000-7f269a843000 ---p 00008000 08:01 3489                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
2021-12-07T12:16:45.0468881Z 7f269a843000-7f269a844000 r--p 00008000 08:01 3489                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
2021-12-07T12:16:45.0469889Z 7f269a844000-7f269a845000 rw-p 00009000 08:01 3489                       /usr/lib/x86_64-linux-gnu/librt-2.31.so
2021-12-07T12:16:45.0470956Z 7f269a845000-7f269a84c000 r--p 00000000 08:01 3481                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-12-07T12:16:45.0472098Z 7f269a84c000-7f269a85d000 r-xp 00007000 08:01 3481                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-12-07T12:16:45.0473246Z 7f269a85d000-7f269a862000 r--p 00018000 08:01 3481                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-12-07T12:16:45.0474359Z 7f269a862000-7f269a863000 r--p 0001c000 08:01 3481                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-12-07T12:16:45.0475483Z 7f269a863000-7f269a864000 rw-p 0001d000 08:01 3481                       /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
2021-12-07T12:16:45.0476344Z 7f269a864000-7f269a868000 rw-p 00000000 00:00 0 
2021-12-07T12:16:45.0477004Z 7f269a868000-7f269a869000 r-xp 00000000 00:00 0 
2021-12-07T12:16:45.0477662Z 7f269a869000-7f269a870000 r-xp 00000000 00:00 0 
2021-12-07T12:16:45.0478727Z 7f269a870000-7f269a877000 r--s 00000000 08:01 3766                       /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
2021-12-07T12:16:45.0479621Z 7f269a877000-7f269a879000 rw-p 00000000 00:00 0 
2021-12-07T12:16:45.0480475Z 7f269a879000-7f269a87a000 r--p 00000000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
2021-12-07T12:16:45.0481460Z 7f269a87a000-7f269a89d000 r-xp 00001000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
2021-12-07T12:16:45.0482442Z 7f269a89d000-7f269a8a5000 r--p 00024000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
2021-12-07T12:16:45.0483340Z 7f269a8a5000-7f269a8a6000 r-xp 00000000 00:00 0 
2021-12-07T12:16:45.0484229Z 7f269a8a6000-7f269a8a7000 r--p 0002c000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
2021-12-07T12:16:45.0485229Z 7f269a8a7000-7f269a8a8000 rw-p 0002d000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
2021-12-07T12:16:45.0486049Z 7f269a8a8000-7f269a8a9000 rw-p 00000000 00:00 0 
2021-12-07T12:16:45.0486862Z 7ffe42b68000-7ffe43b67000 rwxp 00000000 00:00 0                          [stack]
2021-12-07T12:16:45.0487743Z 7ffe43ba6000-7ffe43baa000 r--p 00000000 00:00 0                          [vvar]
2021-12-07T12:16:45.0488659Z 7ffe43baa000-7ffe43bac000 r-xp 00000000 00:00 0                          [vdso]
2021-12-07T12:16:45.0489721Z ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
2021-12-07T12:16:45.0490296Z 
2021-12-07T12:16:45.0490505Z 
2021-12-07T12:16:45.0490833Z [NOTE]
2021-12-07T12:16:45.0491493Z You may have encountered a bug in the Ruby interpreter or extension libraries.
2021-12-07T12:16:45.0492300Z Bug reports are welcome.
2021-12-07T12:16:45.0493212Z For details: https://www.ruby-lang.org/bugreport.html
```

</details>

**Comment by ronaldtse** [comment]
This may be related to this: https://github.com/pmq20/ruby-packer/issues/159

Apparently reading files from ruby-packer memfs is not thread safe.

**Comment by ronaldtse** [comment]
Maybe we can do this!

We could replace this code:
https://github.com/metanorma/packed-mn/blob/c1904865ca7e5375ecb4acbf2e5e86fe682ebb9f/bin/metanorma#L178-L186

With:

https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/X509/Store.html
```ruby
cert_store = OpenSSL::X509::Store.new
cert_store.add_file 'cacert.pem'
```

https://github.com/ruby/ruby/blob/007e439fe965871c73127928f7244ebb96a86e58/test/rubygems/test_bundled_ca.rb#L18-L26
```ruby
  def bundled_certificate_store
    store = OpenSSL::X509::Store.new

    Gem::Request.get_cert_files.each do |ssl_cert|
      store.add_file ssl_cert
    end

    store
  end
```

https://github.com/ruby/ruby/blob/007e439fe965871c73127928f7244ebb96a86e58/test/rubygems/test_bundled_ca.rb#L31-L33
```ruby
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER
    http.cert_store = bundled_certificate_store
```

**Comment by ronaldtse** [comment]
Trying here: https://github.com/metanorma/packed-mn/pull/132/commits/7de83a20b0afe484c69feb5f8d82b0422755c18a

**Comment by ronaldtse** [comment]
This was temporarily fixed here: https://github.com/metanorma/packed-mn/pull/132/commits/09ffacf8c95b9c42a56c997650161679b4af2c02
