### ISSUE TITLE
[relaton-ieee] time out on  fetching "IEEE Std 1516"

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#148]
All platforms
```
[relaton-ieee] ("IEEE Std 1516") fetching...
#<Thread:0x00007fe456202640 /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/workers_pool.rb:10 run> terminated with exception (report_on_exception is true):
/__tebako_memfs__/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '' (JSON::ParserError)
	from /__tebako_memfs__/lib/ruby/2.7.0/json/common.rb:156:in `parse'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/hit_collection.rb:22:in `initialize'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/ieee_bibliography.rb:7:in `new'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/ieee_bibliography.rb:7:in `search'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/ieee_bibliography.rb:20:in `get'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-ieee-1.9.4/lib/relaton_ieee/processor.rb:20:in `get'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:432:in `net_retry'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:417:in `new_bib_entry'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:397:in `check_bibliocache'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:74:in `fetch'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/db.rb:110:in `block in fetch_async'
	from /__tebako_memfs__/lib/ruby/gems/2.7.0/gems/relaton-1.9.8/lib/relaton/workers_pool.rb:11:in `block (2 levels) in initialize'
Error: The action has timed out.
```

_Originally posted by @maxirmx in https://github.com/metanorma/packed-mn/issues/147#issuecomment-1024530154_

**Comment by andrew2net** [comment]
fixed in relaton-ieee v 1.10.0
