### ISSUE TITLE
(URGENT) Crash in Metanorma

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#203]
Metanorma ISO 2.4.4 crashing. Do we know why?

```
Style: (XML Line 000006): No French Title Intro!
Style: (XML Line 000008): No French Title!
Style: (XML Line 000010): No French Title Part!
Style: (XML Line 000722): undated reference ISO/IEC 15444-2 should not contain specific elements
Syntax Valid!
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/isodoc/iso/presentation_xml_convert.rb:110:in `admonition1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/presentation_function/block.rb:74:in `block in admonition'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.4-x86_64-darwin/lib/nokogiri/xml/node_set.rb:235:in `block in each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.4-x86_64-darwin/lib/nokogiri/xml/node_set.rb:234:in `upto'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.4-x86_64-darwin/lib/nokogiri/xml/node_set.rb:234:in `each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/presentation_function/block.rb:74:in `admonition'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/isodoc/iso/presentation_xml_convert.rb:26:in `block'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/presentation_xml_convert.rb:40:in `conversions'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/presentation_xml_convert.rb:23:in `convert1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/isodoc/iso/presentation_xml_convert.rb:18:in `convert1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/convert.rb:150:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/metanorma/iso/processor.rb:67:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:159:in `process_output_unthreaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:145:in `process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:119:in `process_ext'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:107:in `block in process_exts'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:106:in `each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:106:in `process_exts'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:37:in `compile'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/compiler.rb:45:in `compile_file'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/compiler.rb:30:in `compile'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/compiler.rb:35:in `compile'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/site_generator.rb:91:in `compile'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/site_generator.rb:31:in `block in generate'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/site_generator.rb:31:in `each'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/site_generator.rb:31:in `generate'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/site_generator.rb:26:in `generate'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli/commands/site.rb:33:in `generate'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.7.2/lib/metanorma/cli.rb:34:in `start'
/__tebako_memfs__/local/metanorma:217:in `<main>'
No such file or directory @ rb_sysopen - /Users/lrosenth/ISO_Authoring/19005-4/_site/documents/19005-4.presentation.xml
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/convert.rb:147:in `read'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/convert.rb:147:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/html_convert.rb:26:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/metanorma/iso/processor.rb:49:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:150:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:142:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
No such file or directory @ rb_sysopen - /Users/lrosenth/ISO_Authoring/19005-4/_site/documents/19005-4.presentation.xml
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/isodoc/iso/word_convert.rb:55:in `read'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/isodoc/iso/word_convert.rb:55:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/metanorma/iso/processor.rb:55:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:150:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:142:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
No such file or directory @ rb_sysopen - /Users/lrosenth/ISO_Authoring/19005-4/_site/documents/19005-4.presentation.xml
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/xslfo_convert.rb:57:in `read'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.5.5/lib/isodoc/xslfo_convert.rb:57:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-iso-2.4.4/lib/metanorma/iso/processor.rb:58:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:150:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/compile.rb:142:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.10/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

**Comment by maxirmx** [comment]
It is "crashing" because it tries to open file and cannot find it
```No such file or directory @ rb_sysopen - /Users/lrosenth/ISO_Authoring/19005-4/_site/documents/19005-4.presentation.xml```

If there is a reason to think that it is not just a missing file I need the following information
- the method that was used to install  packed-mn 
- site data that was processed
- full log including command line with arguments

**Comment by opoudjis** [comment]
We have indication of the issue from the client:

> Figured it out doing some debugging here…
 
> Turned out I had an empty admonition
 
````
[EDITOR]
====
// comment here
====
````
 
> As soon as I uncommented the comment, it worked fine.   So apparently MN doesn’t like ‘em empty…

**Comment by opoudjis** [comment]
Unassigning you @maxirmx, I'll fix tomorrow
