### ISSUE TITLE
Bundler 2.5 crashes (on Windows) during metanorma packaging

### ISSUE THREAD

**Issue by maxirmx** [metanorma/packed-mn#228]
```
pushd build & aibika --console --gemfile Gemfile --gem-full --add-all-core --icon metanorma.ico \
		--no-autoload \
		metanorma cacert.pem.mozilla & popd
=== Loading script to check dependencies
Need to specify a file to process
[1084, #<Thread:0x000001ac28979750 run>, #<NameError: uninitialized constant Bundler::SharedHelpers

      Bundler::SharedHelpers.filesystem_access(loaded_from, :read) do
             ^^^^^^^^^^^^^^^>, ["C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:151:in `data'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/stub_specification.rb:155:in `name'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/stub_specification.rb:88:in `activated?'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1049:in `block in find_active_stub_by_path'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1048:in `each'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1048:in `find'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1048:in `find_active_stub_by_path'", "<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:94:in `require'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:211:in `<module:Gem>'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:33:in `<top (required)>'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `require_relative'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `<top (required)>'", "<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:249:in `block in find_gem_files'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `each'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `find_gem_files'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:451:in `build_exe'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/bin/aibika:15:in `block in <top (required)>'"]]
[1084, #<Thread:0x000001ac28979750 run>, #<RuntimeError: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true>, ["<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require'", "<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:211:in `<module:Gem>'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:33:in `<top (required)>'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `require_relative'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `<top (required)>'", "<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:249:in `block in find_gem_files'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `each'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `find_gem_files'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:451:in `build_exe'", "C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/bin/aibika:15:in `block in <top (required)>'"]]
<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	from <internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:249:in `block in find_gem_files'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `each'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `find_gem_files'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:451:in `build_exe'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/bin/aibika:15:in `block in <top (required)>'
<internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `ensure in require': CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true (RuntimeError)
	from <internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:211:in `<module:Gem>'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:33:in `<top (required)>'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `require_relative'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `<top (required)>'
	from <internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:249:in `block in find_gem_files'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `each'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `find_gem_files'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:451:in `build_exe'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/bin/aibika:15:in `block in <top (required)>'
C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:151:in `data': uninitialized constant Bundler::SharedHelpers (NameError)

      Bundler::SharedHelpers.filesystem_access(loaded_from, :read) do
             ^^^^^^^^^^^^^^^
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/stub_specification.rb:155:in `name'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/stub_specification.rb:88:in `activated?'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1049:in `block in find_active_stub_by_path'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1048:in `each'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1048:in `find'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/specification.rb:1048:in `find_active_stub_by_path'
	from <internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:94:in `require'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:211:in `<module:Gem>'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler/rubygems_ext.rb:33:in `<top (required)>'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `require_relative'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/bundler-2.5.10/lib/bundler.rb:10:in `<top (required)>'
	from <internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from <internal:C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:96:in `require'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:249:in `block in find_gem_files'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `each'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:248:in `find_gem_files'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/lib/aibika.rb:451:in `build_exe'
	from C:/hostedtoolcache/windows/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/aibika-1.3.14/bin/aibika:15:in `block in <top (required)>'
=== Scanning Gemfile
```

**Comment by maxirmx** [comment]
It is something specific to metanorma because all aibika tests pass

**Comment by CAMOBAP** [comment]
@ronaldtse mentioned that tamtebaco is ready for windows so I think make sense to move to it, I will take it
