### ISSUE TITLE
Add in all mn-samples-* tests just like metanorma-docker

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#31]
Just like https://github.com/metanorma/metanorma-docker/pull/76

Thanks!

**Comment by CAMOBAP** [comment]
OSX passed successfully but it failed on Linux because of npm/puppeteer missing. 

```
Error: Cannot find module '/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.0.3/bin/metanorma-pdf.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.0.24/lib/isodoc/pdf_convert.rb:33:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-itu-1.0.13/lib/metanorma/itu/processor.rb:36:in `output'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:208:in `block in process_extensions'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:199:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:199:in `process_extensions'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.0.3/lib/metanorma/compile.rb:20:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/compiler.rb:41:in `compile_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/compiler.rb:29:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/compiler.rb:33:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli/command.rb:36:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.2.12/lib/metanorma/cli.rb:74:in `start'
	from /__enclose_io_memfs__/local/metanorma:82:in `<main>'
```

Isn't clear why `metanorma-iso:1.0.3` downloaded at all if in Gemfile.lock we have `metanorma-iso (~> 1.3.0)`

To be continued...

**Comment by CAMOBAP** [comment]
Fixed after update Gemfile.lock
