### ISSUE TITLE
itu, ogc tests failed

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#75]
- https://github.com/metanorma/packed-mn/actions/runs/444220306
 - https://github.com/metanorma/packed-mn/actions/runs/444220304

**Comment by CAMOBAP** [comment]
- itu - we moved to site-gen command
 - ogc - https://github.com/relaton/relaton-bib/issues/39 - fixed already waiting for the release

**Comment by ronaldtse** [comment]
Ping @CAMOBAP on progress. Thanks!

**Comment by CAMOBAP** [comment]
Per https://github.com/metanorma/mn-samples-gb/issues/38#issuecomment-790599432 make sense to remove gb

**Comment by CAMOBAP** [comment]
Current status:
 - ietf itu ogc iho - broken on each platform (corresponding tickets reported)
 - bipm - broken only on windows

**Comment by ronaldtse** [comment]
@CAMOBAP the ITU tests pass now but are unable to generate PDF due to this:

```
[info]: Compiling /Users/runner/work/mn-samples-itu/mn-samples-itu/sources/T-TUT-CABLETV-2020.adoc ...
14075
[relaton-itu] ("ITU-T H.265 (V7)") fetching...
14076
encoding error : input conversion failed due to input error, bytes 0x8F 0x6F 0x82 0xB5
14077
encoding error : input conversion failed due to input error, bytes 0x8F 0x6F 0x82 0xB5
14078
[relaton-itu] ("ITU-T H.265 (V7)") found ITU-T H.265
14079
[relaton-itu] ("ITU-T J.207") fetching...
14080
[relaton-itu] ("ITU-T J.207") found ITU-T J.207
14081
[relaton-itu] ("ITU-R BT.2267-10") fetching...
14082
[relaton-itu] WARNING: no match found online for ITU-R BT.2267-10. The code must be exactly like it is on the standards website.
14083
[relaton-itu] The provided document part may not exist, or the document may no longer be published in parts.
14084
[relaton-w3c] ("W3C WebArch") fetching...
14085
[relaton-w3c] ("W3C WebRTC") fetching...
14086
[relaton-w3c] ("W3C WebSocket") fetching...
14087
Metanorma XML Style Warning: (XML Line 000156): Hanging paragraph in clause
14088
Metanorma XML Style Warning: (XML Line 000168): Hanging paragraph in clause
14089
Metanorma XML Style Warning: (XML Line 000175): Hanging paragraph in clause
14090
Metanorma XML Style Warning: (XML Line 000179): Hanging paragraph in clause
14091
Style: No Keywords have been provided
14092
Style: ITU-T JSTP-IBBDTV does not match ITU document identifier conventions
14093
Style: (XML Line 000140): Requirement possibly in preface: However, the CATV systems have not been able to support all such digital services developments as the CATV systems must satisfy certain requirements in order to support them
14094
Syntax Valid!
14095
wrong number of arguments (given 4, expected 3)
14096
/__enclose_io_memfs__/local/metanorma:127:in `convert'
14097
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/output/xslfo.rb:10:in `convert'
14098
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.5.3/lib/isodoc/xslfo_convert.rb:39:in `convert'
14099
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-itu-1.2.14/lib/metanorma/itu/processor.rb:45:in `output'
14100
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:260:in `block in process_extensions'
14101
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:249:in `each'
14102
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:249:in `process_extensions'
14103
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:28:in `compile'
14104
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/compiler.rb:45:in `compile_file'
14105
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/compiler.rb:30:in `compile'
14106
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/compiler.rb:35:in `compile'
14107
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:77:in `compile'
14108
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:24:in `block in generate'
14109
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:24:in `each'
14110
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:24:in `generate'
14111
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/site_generator.rb:19:in `generate'
14112
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli/commands/site.rb:23:in `generate'
14113
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
14114
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
14115
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
14116
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
14117
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
14118
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
14119
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
14120
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
14121
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
14122
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.5/lib/metanorma/cli.rb:67:in `start'
14123
```

Isn't this fixed? Or not released?

**Comment by CAMOBAP** [comment]
@ronaldtse yep exactly it's fixed but not released yet + one more problem is blocking release for linux/macos https://github.com/metanorma/packed-mn/issues/83

**Comment by CAMOBAP** [comment]
Separate tickets created for all failed flavors:
 - `ietf` - wait for release of https://github.com/metanorma/metanorma-ietf/commit/ca75ea3
 - `itu` - https://github.com/relaton/relaton-bib/issues/44
 - `ogc`  - https://github.com/metanorma/mn-samples-ogc/issues/119
