### ISSUE TITLE
BIPM The git source https://github.com/metanorma/metanorma-cli is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#80]
https://github.com/metanorma/mn-samples-bipm/pull/30/checks?check_run_id=2006725491

```
C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/git/git_proxy.rb:223:in `allowed_with_path': The git source https://github.com/metanorma/metanorma-cli is not yet checked out. Please run `bundle install` before trying to start your application (Bundler::GitError)
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/git/git_proxy.rb:193:in `find_local_revision'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/git/git_proxy.rb:65:in `revision'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/git.rb:228:in `revision'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/git.rb:95:in `install_path'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/path.rb:131:in `expanded_path'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/path.rb:172:in `load_spec_files'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/git.rb:203:in `load_spec_files'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/path.rb:105:in `local_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/source/git.rb:170:in `specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/definition.rb:766:in `block in converge_locked_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/definition.rb:752:in `each'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/definition.rb:752:in `converge_locked_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/definition.rb:256:in `resolve'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/definition.rb:170:in `specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/definition.rb:240:in `specs_for'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/definition.rb:222:in `requested_specs'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/runtime.rb:91:in `block in definition_method'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/runtime.rb:20:in `setup'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler.rb:148:in `setup'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/ui/shell.rb:136:in `with_level'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/ui/shell.rb:88:in `silence'
	from C:/Users/runneradmin/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/gems/2.4.0/gems/bundler-2.2.11/lib/bundler/setup.rb:20:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr58B8.tmp/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr58B8.tmp/src/metanorma:5:in `<main>'
```

**Comment by CAMOBAP** [comment]
The same issue happens for other gems

**Comment by CAMOBAP** [comment]
Fixed
