### ISSUE TITLE
Failed to initialize SevenZipRuby (RuntimeError)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#83]
`metanorma site generate build/cc -c build/cc/metanorma.yml --agree-to-terms`

```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/seven_zip_ruby-1.3.0/lib/seven_zip_ruby.rb:26:in `<top (required)>': Failed to initialize SevenZipRuby (RuntimeError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/extractors/seven_zip_extractor.rb:1:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/extractors/seven_zip_extractor.rb:1:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/extractors.rb:7:in `require_relative'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate/extractors.rb:7:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate.rb:4:in `require_relative'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/excavate-0.1.1/lib/excavate.rb:4:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:2:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font_installer.rb:2:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:1:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist/font.rb:1:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist.rb:10:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/fontist-1.8.8/lib/fontist.rb:10:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:5:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma/compile.rb:5:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma.rb:12:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.6/lib/metanorma.rb:12:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.5.3/lib/isodoc/pdf_convert.rb:4:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.5.3/lib/isodoc/pdf_convert.rb:4:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.5.3/lib/isodoc.rb:21:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/isodoc-1.5.3/lib/isodoc.rb:21:in `<top (required)>'
	from /__enclose_io_memfs__/local/metanorma:168:in `require'
	from /__enclose_io_memfs__/local/metanorma:168:in `<main>'
```

**Comment by ronaldtse** [comment]
@alexeymorozov would you be able to help here?

**Comment by CAMOBAP** [comment]
@ronaldtse to be on the same page it' is clearly packed-mn issue which probably related to the wrong path in memfs

**Comment by ronaldtse** [comment]
OK

**Comment by CAMOBAP** [comment]
Fixed
