### ISSUE TITLE
Investigate ITU flavor failure

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#88]
Initially https://github.com/relaton/relaton-bib/issues/44 was reported, but this issue doesn't reproduce on `bundle exec metanorma site generate build/itu -o site/itu -c build/itu/metanorma.yml --agree-to-terms` (ruby script call)

But it happens for both `ocra` and `ruby-packer` executables, I have double-checked gem versions in those cases it's the same

```
C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:440:in `block in symbolize': undefined method `to_sym' for 404:Integer (NoMethodError)
Did you mean?  to_s
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:439:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:439:in `reduce'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:439:in `symbolize'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:12:in `hash_to_bib'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-itu-1.7.5/lib/relaton_itu/hit_collection.rb:31:in `initialize'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:22:in `new'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:22:in `search'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:84:in `search_filter'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:124:in `itubib_get1'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:43:in `get'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-itu-1.7.5/lib/relaton_itu/processor.rb:17:in `get'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-1.7.6/lib/relaton/db.rb:380:in `net_retry'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-1.7.6/lib/relaton/db.rb:366:in `new_bib_entry'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-1.7.6/lib/relaton/db.rb:348:in `check_bibliocache'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/relaton-1.7.6/lib/relaton/db.rb:60:in `fetch'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:69:in `fetch_ref'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref.rb:191:in `refitem1'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref.rb:183:in `refitem'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref.rb:234:in `reference1'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:14:in `block (2 levels) in reference'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:14:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:14:in `block in reference'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `new'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `with'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:13:in `reference'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/lists.rb:38:in `ulist'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/list.rb:30:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:26:in `block in bibliography_parse'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:394:in `insert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:23:in `bibliography_parse'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/section.rb:77:in `block in section'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `new'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `with'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/section.rb:62:in `section'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:190:in `block in middle'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:394:in `insert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:189:in `middle'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:161:in `block in makexml1'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `new'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/nokogiri-1.10.10-x64-mingw32/lib/nokogiri/xml/builder.rb:254:in `with'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:161:in `makexml1'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:167:in `makexml'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-itu-1.2.15/lib/asciidoctor/itu/converter.rb:38:in `makexml'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:142:in `document'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-1.2.7/lib/metanorma/input/asciidoc.rb:24:in `process'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-1.2.7/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-1.2.7/lib/metanorma/compile.rb:137:in `process_input'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-1.2.7/lib/metanorma/compile.rb:24:in `compile'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:30:in `compile'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:35:in `compile'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:81:in `compile'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:23:in `generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/commands/site.rb:25:in `generate'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/lib/ruby/gems/2.4.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli.rb:67:in `start'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr52B6.tmp/src/metanorma:198:in `<main>'
```

**Comment by CAMOBAP** [comment]
Tested on ruby 2.4.1 doesn't reproduces outside ruby-packer

**Comment by CAMOBAP** [comment]
Fixed after gem update

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
