### ISSUE TITLE
(URGENT) relaton-iec dies when reading "ISO/IEC DIR 2"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#99]
https://github.com/metanorma/mn-samples-ogc/runs/2702879797?check_suite_focus=true

```
[relaton-iec] ("ISO/IEC DIR 2") fetching...
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iec-1.7.8/lib/relaton_iec/hit_collection.rb:28:in `to_all_parts': undefined local variable or method `lang' for #<RelatonIec::HitCollection:0x000000001bea9848> (NameError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iec-1.7.8/lib/relaton_iec/iec_bibliography.rb:169:in `results_filter'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iec-1.7.8/lib/relaton_iec/iec_bibliography.rb:208:in `iecbib_get'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iec-1.7.8/lib/relaton_iec/iec_bibliography.rb:46:in `get'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iso-1.7.4/lib/relaton_iso/iso_bibliography.rb:53:in `get'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iso-1.7.4/lib/relaton_iso/processor.rb:19:in `get'
```

This is blocking generation of mn-samples-ogc.

**Comment by andrew2net** [comment]
@ronaldtse this issue was fixed in relaton-iec v 1.8.0

**Comment by ronaldtse** [comment]
Thanks @andrew2net , @CAMOBAP can you confirm the fix in metanorma/mn-samples-ogc#121? Thanks.

**Comment by CAMOBAP** [comment]
Testing...

**Comment by CAMOBAP** [comment]
Fix proved by https://github.com/metanorma/packed-mn/tree/feature/put-back-testing-for-ogc

**Comment by CAMOBAP** [comment]
Waiting for macos before merge
